### ISSUE TITLE
Missing instance

### ISSUE THREAD

**Issue by Sk8erOfBodom** [Maselkov/GW2RPC#2]
Hey, not sure if that's the best place to post about this, but couldn't really find anywhere else, I hope you see this.

The Discovering Scarlet's Breakthrough story instance (from Living World season 2, [wiki link](https://wiki.guildwars2.com/wiki/Discovering_Scarlet%27s_Breakthrough))  is not detected by GW2RPC and causes a crash.

Here's the log from that:
```
2018-01-16 23:17:42,949:CRITICAL:root: GW2RPC has crashed
Traceback (most recent call last):
  File "gw2rpc\gw2rpc.py", line 291, in main_loop
  File "gw2rpc\gw2rpc.py", line 223, in get_activity
  File "gw2rpc\character.py", line 47, in __init__
  File "gw2rpc\character.py", line 55, in _get_profession
  File "gw2rpc\character.py", line 74, in get_spec
KeyError: 'region_name'
```

And thanks for that little program, it's pretty cool!

**Comment by Maselkov** [comment]
Thanks for the report, it's API being inconsistent. Will be fixed in next update.
